''' config file for the project
all values that will be manually tuned and can be tweaked using input will be present here, i dont have to iterate through any of the code myself, these are like global variables that i am going to define
here which can be used to alter throughout the entire code later on without having to mess with codebase'''

from __future__ import annotations
from dataclasses import dataclass
from pathlib import Path
 

BASE_DIR=Path(__file__).resolve().parent.parent
DATA_DIR= BASE_DIR/"data"
MODELS_DIR= BASE_DIR/"models"
LOGS_DIR= BASE_DIR/"logs"
DOCS_DIR=BASE_DIR/"docs"

MODEL_FILENAME="sign_language_model.pkl"
LABEL_ENCODER_FILENAME="label_encoder.pkl"
MODEL_PATH= MODELS_DIR/MODEL_FILENAME
LABEL_ENCODER_PATH=MODELS_DIR/LABEL_ENCODER_FILENAME

#dataset artifacts
RAW_DATA_FILENAME = "collected_data.pickle"
PROCESSED_DATA_FILENAME = "processed_data.pickle"
RAW_DATA_PATH = DATA_DIR / RAW_DATA_FILENAME
PROCESSED_DATA_PATH = DATA_DIR / PROCESSED_DATA_FILENAME


#inference and buffering
CONFIDENCE_THRESHOLD= 0.75
BACKSPACE_CONFIDENCE_THRESHOLD=0.85
STABILITY_FRAMES=5
TARGET_FPS=25
WEBCAM_INDEX=0
FRAME_WIDTH=640
FRAME_HEIGHT=480
NO_HAND_SILENCE_SECONDS=0.0

#SENTENCE HANDLING
PAUSE_COMMIT_SECONDS=2.5
PAUSE_CONFIRM_SECONDS=1.5

#TTS
TTS_BACKEND="pyttsx3"
TTS_RATE=175
TTS_VOLUME=1.0
TTS_INTERRUPT_ENABLED=True

#ui automation
TYPING_STRATEGY="clipboard"
TYPING_SPEED=0.05
CLIPBOARD_RESTORE_TIMEOUT=5.0
BACKSPACE_REPEAT_DELAY=0.01

#IPC
BACKSPACE_TOKEN = "__BACKSPACE__"
COMMIT_TOKEN = "__COMMIT__"
QUEUE_TIMEOUT = 1.0

# Logging
LOG_LEVEL = "INFO"
LOG_TO_FILE = True
LOG_FORMAT = "%(asctime)s | %(levelname)s | %(name)s | %(message)s"
LOG_FILE_NAME = "signbridge.log"

# Training defaults
TRAIN_SPLIT_RATIO = 0.2
RANDOM_STATE = 42
RF_N_ESTIMATORS = 100
RF_MAX_DEPTH = 15
RF_MIN_SAMPLES_LEAF = 5
MIN_CLASS_ACCURACY = 0.85
TEST_ACCURACY_TARGET = 0.90

# Feature extraction
LANDMARKS_PER_HAND = 21
FEATURE_DIMENSIONS = 48
MAX_HANDS = 2

# MediaPipe
MP_STATIC_IMAGE_MODE = False
MP_MAX_NUM_HANDS = 2
MP_MIN_DETECTION_CONFIDENCE = 0.3
MP_MIN_TRACKING_CONFIDENCE = 0.3

# Misc
DEFAULT_ENCODING = "utf-8"


@dataclass(frozen=True)
class Config:
    base_dir:Path=BASE_DIR
    data_dir:Path=DATA_DIR
    models_dir:Path=MODELS_DIR
    logs_dir:Path=LOGS_DIR
    docs_dir:Path=DOCS_DIR
    
    model_path:Path=MODEL_PATH
    label_encoder_path:Path=LABEL_ENCODER_PATH
    raw_data_path:Path=RAW_DATA_PATH
    processed_data_path:Path=PROCESSED_DATA_PATH
    
    CONFIDENCE_THRESHOLD:float=CONFIDENCE_THRESHOLD
    BACKSPACE_CONFIDENCE_THRESHOLD:float=BACKSPACE_CONFIDENCE_THRESHOLD
    STABILITY_FRAMES:int=STABILITY_FRAMES
    TARGET_FPS:int=TARGET_FPS
    WEBCAM_INDEX:int=WEBCAM_INDEX
    FRAME_WIDTH:int=FRAME_WIDTH
    FRAME_HEIGHT:int=FRAME_HEIGHT
    
    PAUSE_COMMIT_SECONDS:float=PAUSE_COMMIT_SECONDS
    PAUSE_CONFIRM_SECONDS:float=PAUSE_CONFIRM_SECONDS
    
    TTS_BACKEND:str=TTS_BACKEND
    TTS_RATE:int=TTS_RATE
    TTS_VOLUME:float=TTS_VOLUME
    TTS_INTERRUPT_ENABLED:bool=TTS_INTERRUPT_ENABLED
    
    TYPING_STRATEGY:str=TYPING_STRATEGY
    TYPING_SPEED:float=TYPING_SPEED
    CLIPBOARD_RESTORE_TIMEOUT:float=CLIPBOARD_RESTORE_TIMEOUT
    BACKSPACE_REPEAT_DELAY:float=BACKSPACE_REPEAT_DELAY
    
    BACKSPACE_TOKEN:str=BACKSPACE_TOKEN
    COMMIT_TOKEN:str=COMMIT_TOKEN
    QUEUE_TIMEOUT:float=QUEUE_TIMEOUT
    
    LOG_LEVEL:str=LOG_LEVEL
    LOG_TO_FILE:bool=LOG_TO_FILE
    LOG_FORMAT:str=LOG_FORMAT
    LOG_FILE_NAME:str=LOG_FILE_NAME
    
    TRAIN_SPLIT_RATIO:float=TRAIN_SPLIT_RATIO
    RANDOM_STATE:int=RANDOM_STATE
    RF_N_ESTIMATORS:int=RF_N_ESTIMATORS
    RF_MAX_DEPTH:int=RF_MAX_DEPTH
    RF_MIN_SAMPLES_LEAF:int=RF_MIN_SAMPLES_LEAF
    MIN_CLASS_ACCURACY:float=MIN_CLASS_ACCURACY
    TEST_ACCURACY_TARGET:float=TEST_ACCURACY_TARGET
    
    LANDMARKS_PER_HAND:int=LANDMARKS_PER_HAND
    FEATURE_DIMENSIONS:int=FEATURE_DIMENSIONS
    MAX_HANDS:int=MAX_HANDS
    
    MP_STATIC_IMAGE_MODE:bool=MP_STATIC_IMAGE_MODE
    MP_MAX_NUM_HANDS:int=MP_MAX_NUM_HANDS
    MP_MIN_DETECTION_CONFIDENCE:float=MP_MIN_DETECTION_CONFIDENCE
    MP_MIN_TRACKING_CONFIDENCE:float=MP_MIN_TRACKING_CONFIDENCE
    
    DEFAULT_ENCODING:str=DEFAULT_ENCODING
    
def ensure_runtime_dirs() -> None:
    for directory in (DATA_DIR, MODELS_DIR, LOGS_DIR): #creates runtime dirs if they dont exist already
        directory.mkdir(parents=True, exist_ok=True)

ensure_runtime_dirs()
DEFAULT_CONFIG=Config()
    
